# Generated by Django 5.2.5 on 2025-10-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_city_status_country_status_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
