# Generated by Django 5.2.5 on 2025-10-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_city_status_alter_country_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
    ]
